[package]
name = "oven"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.0"

nalgebra.workspace = true

[build-dependencies]
csv = "1.0.2"

nalgebra.workspace = true

common = { path = "../common" }

[features]
strict = []
