[package]
name = "common"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
flatbuffers = "0.5.0"
lazy_static = "1.1.0"
smallvec = "0.6.9"

nalgebra.workspace = true

rlbot.workspace = true

[dev-dependencies]
chip = "0.0.6"

[features]
strict = []
