[package]
name = "dom"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
nalgebra.workspace = true

rlbot.workspace = true

common = { path = "../common" }

[dev-dependencies]
chip = "0.0.6"

[features]
strict = []
